Added analyse-pcap.

diff --git a/wlan-cap b/wlan-cap
--- a/wlan-cap
+++ b/wlan-cap
@@ -1,6 +1,8 @@
 #!/bin/bash
 # Script to easily set your wireless card in promiscuous mode and show the IEEE 802.11 frames that are flowing around you.
 
+# Always exit on errors
+set -e
 # Undefined variables, we don't like you
 # set -u
 # ERR traps are inherited by shell functions, command substitutions and
@@ -20,13 +22,12 @@ if [[ "$1" == "start" ]]; then
     if [[ -z "`airmon-ng |grep mon0`" ]]; then
         airmon-ng start wlan0
     fi
-    # airodump-ng --manufacturer --uptime mon0
-    airodump-ng --uptime mon0
+    airodump-ng --manufacturer --uptime mon0
     if [[ $? != 0 ]]; then
         airodump-ng --uptime mon0
     fi
 elif [[ "$1" == "stop" ]]; then
-    killall 'airodump-ng'
+    killall 'airodump-ng' || true
     airmon-ng stop mon0
     airmon-ng stop wlan0
     service network-manager start
