Made rfkill more generic.

diff --git a/wlan-cap b/wlan-cap
--- a/wlan-cap
+++ b/wlan-cap
@@ -1,14 +1,27 @@
 #!/bin/bash
+#
+# Always exit on errors
+set -e
+# Undefined variables, we don't like you
+set -u
+# ERR traps are inherited by shell functions, command substitutions and
+# commands executed in a subshell environment.
+set -E
 
 if [ "$1" == "start" ]; then
     service network-manager stop
-    rfkill unblock 0
-    rfkill unblock 2
-    rfkill unblock 0
-    rfkill unblock 2
+    # Unblock all wireless cards {{{
+    for count in `seq 2`;do
+        rfkill list |grep Wireless|while read rfkill_line;do
+            rfkill unblock ${rfkill_line:0:1}
+        done
+    done
     rfkill list
-    airmon-ng start wlan0
-    airodump-ng wlan0
+    # }}}
+    if [[ -z "`airmon-ng |grep mon0`" ]];then
+        airmon-ng start wlan0
+    fi
+    airodump-ng mon0
 elif [ "$1" == "stop" ]; then
     airmon-ng stop mon0
     airmon-ng stop wlan0
